import function as f
# print(f.revlist([2,4,5,6]))
# print(f.rotating(4,[1,2,3,4,5]))
# print(f.sortlists([1,5,2],[6,7,9]))
# print(f.numtoarr(123))
# print(f.kthlargest([6,2,0,1,8,],3))
print(f.morsetotext('--. . . -.- ... -....- ..-. --- .-. -....- --. . . -.-'))
#print(f.mulmatrices([[1,2],[4,5]],[[4,5],[1,2]]))
# print(f.sortByLength2([['a','b','c'],['d','e'],['f','g','h'],['d','e'],['i','j','k','l'],['m','n'],['o']]))
# print(f.dsforgraph())
# print(f.rps('rock'))